=== renato37/Otvoreno-racunarstvo-laboratorij/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1604994701.json", 
	"title": "Glazbeni instrumenti", 
	"type": "array",
    "description": "Komponente koje opisuju glazbene instrumente",
	"default": [],
	"items":{
		"$id": "#root/items", 
		"title": "Items", 
		"type": "object",
		"required": [
			"naziv",
			"wikipedija",
			"vrsta_instrumenta",
			"zemlja_podrijetla",
			"stoljeće_pojave",
			"glazbeni_žanrovi",
			"dijelovi",
			"način_sviranja",
			"najpoznatiji_izvođači",
			"najpoznatiji_proizvođači"
		],
		"properties": {
			"naziv": {
				"$id": "#root/items/naziv", 
				"title": "Naziv", 
				"type": "string",
				"default": "",
				"examples": [
					"Klasična gitara"
				],
				"pattern": "^.*$"
			},
			"wikipedija": {
				"$id": "#root/items/wikipedija", 
				"title": "Wikipedija", 
				"type": "string",
				"default": "",
				"examples": [
					"https://en.wikipedia.org/wiki/Classical_guitar"
				],
				"pattern": "^.*$"
			},
			"vrsta_instrumenta": {
				"$id": "#root/items/vrsta_instrumenta", 
				"title": "Vrsta_instrumenta", 
				"type": "string",
				"default": "",
				"examples": [
					"Kordofon"
				],
				"pattern": "^.*$"
			},
			"zemlja_podrijetla": {
				"$id": "#root/items/zemlja_podrijetla", 
				"title": "Zemlja_podrijetla", 
				"type": "string",
				"default": "",
				"examples": [
					"Španjolska"
				],
				"pattern": "^.*$"
			},
			"stoljeće_pojave": {
				"$id": "#root/items/stoljeće_pojave", 
				"title": "Stoljeće_pojave", 
				"type": "integer",
				"examples": [
					18
				],
				"default": 0
			},
			"glazbeni_žanrovi": {
				"$id": "#root/items/glazbeni_žanrovi", 
				"title": "Glazbeni_žanrovi", 
				"type": "array",
				"default": [],
				"items":{
					"$id": "#root/items/glazbeni_žanrovi/items", 
					"title": "Items", 
					"type": "string",
					"default": "",
					"examples": [
						"Klasika"
					],
					"pattern": "^.*$"
				}
			},
			"dijelovi": {
				"$id": "#root/items/dijelovi", 
				"title": "Dijelovi", 
				"type": "array",
				"default": [],
				"items":{
					"$id": "#root/items/dijelovi/items", 
					"title": "Items", 
					"type": "object",
					"required": [
						"dio",
						"materijal"
					],
					"properties": {
						"dio": {
							"$id": "#root/items/dijelovi/items/dio", 
							"title": "Dio", 
							"type": "string",
							"default": "",
							"examples": [
								"Prve tri žice"
							],
							"pattern": "^.*$"
						},
						"materijal": {
							"$id": "#root/items/dijelovi/items/materijal", 
							"title": "Materijal", 
							"type": "string",
							"default": "",
							"examples": [
								"Najlon"
							],
							"pattern": "^.*$"
						}
					}
				}

			},
			"način_sviranja": {
				"$id": "#root/items/način_sviranja", 
				"title": "Način_sviranja", 
				"type": "string",
				"default": "",
				"examples": [
					"Trzanjem prstima po žicama"
				],
				"pattern": "^.*$"
			},
			"najpoznatiji_izvođači": {
				"$id": "#root/items/najpoznatiji_izvođači", 
				"title": "Najpoznatiji_izvođači", 
				"type": "array",
				"default": [],
				"items":{
					"$id": "#root/items/najpoznatiji_izvođači/items", 
					"title": "Items", 
					"type": "string",
					"default": "",
					"examples": [
						"Joaquín Rodrigo"
					],
					"pattern": "^.*$"
				}
			},
			"najpoznatiji_proizvođači": {
				"$id": "#root/items/najpoznatiji_proizvođači", 
				"title": "Najpoznatiji_proizvođači", 
				"type": "array",
				"default": [],
				"items":{
					"$id": "#root/items/najpoznatiji_proizvođači/items", 
					"title": "Items", 
					"type": "string",
					"default": "",
					"examples": [
						"Cordoba"
					],
					"pattern": "^.*$"
				}
			}
		}
	}

}

=== renato37/Otvoreno-racunarstvo-laboratorij/glazbeni_instrumenti.json
[
   {
      "naziv": "Klasična gitara",
      "wikipedija": "https://hr.wikipedia.org/wiki/Klasična_gitara",
      "vrsta_instrumenta": "Kordofon",
      "zemlja_podrijetla": "Španjolska",
      "stoljeće_pojave": 18,
      "glazbeni_žanrovi": [
         "Klasika",
         "Tango"
      ],
      "dijelovi": [
         {
            "dio": "Prve tri žice",
            "materijal": "Najlon"
         },
         {
            "dio": "Druge tri žice",
            "materijal": "Metal"
         },
         {
            "dio": "Glava",
            "materijal": "Drvo"
         },
         {
            "dio": "Tijelo",
            "materijal": "Drvo"
         },
         {
            "dio": "Vrat",
            "materijal": "Drvo"
         }
      ],
      "način_sviranja": "Trzanjem prstima po žicama",
      "najpoznatiji_izvođači": [
         "Joaquín Rodrigo"
      ],
      "najpoznatiji_proizvođači": [
         "Cordoba",
         "YAMAHA"
      ]
   },
   {
      "naziv": "Klavir",
      "wikipedija": "https://hr.wikipedia.org/wiki/Glasovir",
      "vrsta_instrumenta": "Glazbala s tipkama",
      "zemlja_podrijetla": "Italija",
      "stoljeće_pojave": 18,
      "glazbeni_žanrovi": [
         "Klasika"
      ],
      "dijelovi": [
         {
            "dio": "Tipke",
            "materijal": "Slonovača"
         },
         {
            "dio": "Žice",
            "materijal": "Metal"
         },
         {
            "dio": "Kućište",
            "materijal": "Drvo"
         },
         {
            "dio": "Pedale",
            "materijal": "Metal"
         }
      ],
      "način_sviranja": "Pritiskanjem tipki batić udara po žicama",
      "najpoznatiji_izvođači": [
         "Wolfgang Amadeus Mozart",
         "Johann Sebastian Bach",
         "Ludwig van Beethoven"
      ],
      "najpoznatiji_proizvođači": [
         "FAZIOLI",
         "Grotrian"
      ]
   },
   {
      "naziv": "Električna gitara",
      "wikipedija": "https://hr.wikipedia.org/wiki/Elektri%C4%8Dna_gitara",
      "vrsta_instrumenta": "Kordofon",
      "zemlja_podrijetla": "Amerika",
      "stoljeće_pojave": 20,
      "glazbeni_žanrovi": [
         "Pop",
         "Rock",
         "Jazz",
         "Blues"
      ],
      "dijelovi": [
         {
            "dio": "Žice",
            "materijal": "Metal"
         },
         {
            "dio": "Glava",
            "materijal": "Drvo"
         },
         {
            "dio": "Tijelo",
            "materijal": "Drvo"
         },
         {
            "dio": "Vrat",
            "materijal": "Drvo"
         }
      ],
      "način_sviranja": "Trzanjem trzalicom po žicama",
      "najpoznatiji_izvođači": [
         "Jimi Hendrix",
         "Eric Clapton",
         "Jimmy Page",
         "Jeff Beck"
      ],
      "najpoznatiji_proizvođači": [
         "Gibson",
         "Fender",
         "Ibanez",
         "Epiphone"
      ]
   },
   {
      "naziv": "Tambura",
      "wikipedija": "https://hr.wikipedia.org/wiki/Tambura",
      "vrsta_instrumenta": "Kordofon",
      "zemlja_podrijetla": "Hrvatska",
      "stoljeće_pojave": 14,
      "glazbeni_žanrovi": [
         "Pop",
         "Narodna glazba",
         "Jazz"
      ],
      "dijelovi": [
         {
            "dio": "Žice",
            "materijal": "Metal"
         },
         {
            "dio": "Glava",
            "materijal": "Drvo"
         },
         {
            "dio": "Tijelo",
            "materijal": "Drvo"
         },
         {
            "dio": "Vrat",
            "materijal": "Drvo"
         }
      ],
      "način_sviranja": "Trzanjem trzalicom po žicama",
      "najpoznatiji_izvođači": [
         "Mijo Majer",
         "Milan Stahuljak",
         "Siniša Leopold"
      ],
      "najpoznatiji_proizvođači": [
         "Molnar",
         "Kudlik Bela",
         "Križanec"
      ]
   },
   {
      "naziv": "Flauta",
      "wikipedija": "https://hr.wikipedia.org/wiki/Flauta",
      "vrsta_instrumenta": "Aerofon",
      "zemlja_podrijetla": "Njemažka",
      "stoljeće_pojave": 19,
      "glazbeni_žanrovi": [
         "Klasika"
      ],
      "dijelovi": [
         {
            "dio": "Cijela",
            "materijal": "Drvo"
         },
         {
            "dio": "Cijela",
            "materijal": "Metal"
         }
      ],
      "način_sviranja": "Puhanjem se ostvaruje zvuk vibracijom zraka",
      "najpoznatiji_izvođači": [
         "Theobald Boehm",
         "James Galway",
         "James Phelan"
      ],
      "najpoznatiji_proizvođači": [
         "YAMAHA",
         "Junan XuQui Musical Co."
      ]
   },
   {
      "naziv": "Bubnjarski komplet",
      "wikipedija": "https://hr.wikipedia.org/wiki/Bubnjarski_komplet",
      "vrsta_instrumenta": "Udaraljke",
      "zemlja_podrijetla": "Velika Britanija",
      "stoljeće_pojave": 18,
      "glazbeni_žanrovi": [
         "Klasika",
         "Jazz",
         "Blues",
         "Rock",
         "Pop",
         "Hip hop"
      ],
      "dijelovi": [
         {
            "dio": "Činele",
            "materijal": "Metal"
         },
         {
            "dio": "Udaraljke",
            "materijal": "Drvo"
         },
         {
            "dio": "Okvir bubnja",
            "materijal": "Metal"
         },
         {
            "dio": "Bubanj",
            "materijal": "Koža"
         }
      ],
      "način_sviranja": "Udaranjem palica po membranama pojedinih dijelova",
      "najpoznatiji_izvođači": [
         "Roger Taylor",
         "Steven Adler",
         "Charlie Watts",
         "John Bonham"
      ],
      "najpoznatiji_proizvođači": [
         "YAMAHA",
         "Rockers",
         "Gretsch"
      ]
   },
   {
      "naziv": "Sintisajzer",
      "wikipedija": "https://hr.wikipedia.org/wiki/Sintesajzer",
      "vrsta_instrumenta": "Elektrofoni",
      "zemlja_podrijetla": "Amerika",
      "stoljeće_pojave": 20,
      "glazbeni_žanrovi": [
         "Rock",
         "Pop"
      ],
      "dijelovi": [
         {
            "dio": "Tipke",
            "materijal": "Plastika"
         },
         {
            "dio": "Kućište",
            "materijal": "Plastika"
         },
         {
            "dio": "Elektronika",
            "materijal": "Tranzistori i diode"
         }
      ],
      "način_sviranja": "Pritiskanjem gumba na tastaturi računalo pušta zvukove određene frekvencije",
      "najpoznatiji_izvođači": [
         "Brockett Parsons",
         "Brittani Washington",
         "Myron McKinley"
      ],
      "najpoznatiji_proizvođači": [
         "Casio",
         "YAMAHA"
      ]
   },
   {
      "naziv": "Gajde",
      "wikipedija": "https://hr.wikipedia.org/wiki/Gajde",
      "vrsta_instrumenta": "Aerofon",
      "zemlja_podrijetla": "Hrvatska",
      "stoljeće_pojave": 18,
      "glazbeni_žanrovi": [
         "Narodna glazba"
      ],
      "dijelovi": [
         {
            "dio": "Mjeh",
            "materijal": "Koža"
         },
         {
            "dio": "Svirale",
            "materijal": "Drvo"
         }
      ],
      "način_sviranja": "Protokom zraka kroz šuplje drvo stvaraju se određeni tonovi",
      "najpoznatiji_izvođači": [
         "Joza Bičanić",
         "Marko Drventić",
         "Adam Vuksanović"
      ],
      "najpoznatiji_proizvođači": [
         "Joza Bičanić",
         "Marko Drventić",
         "Stjepan Večković"
      ]
   },
   {
      "naziv": "Orgulje",
      "wikipedija": "https://hr.wikipedia.org/wiki/Orgulje",
      "vrsta_instrumenta": "Aerofon/Glazbala s tipkama",
      "zemlja_podrijetla": "Francuska",
      "stoljeće_pojave": 8,
      "glazbeni_žanrovi": [
         "Klasika",
         "Crkvena glazba"
      ],
      "dijelovi": [
         {
            "dio": "Tipke",
            "materijal": "Slonovača"
         },
         {
            "dio": "Cijevi",
            "materijal": "Metal"
         },
         {
            "dio": "Kućište",
            "materijal": "Drvo"
         },
         {
            "dio": "Pedale",
            "materijal": "Metal"
         }
      ],
      "način_sviranja": "Strujanjem zraka kroz cijevi različitih dimenzija dolazi do tonova različitih frekvencija",
      "najpoznatiji_izvođači": [
         "Višeslav Jaklin",
         "Milan Hibšer"
      ],
      "najpoznatiji_proizvođači": [
         "Fabing",
         "Fischer"
      ]
   },
   {
      "naziv": "Harmonika",
      "wikipedija": "https://hr.wikipedia.org/wiki/Harmonika",
      "vrsta_instrumenta": "Aerofon",
      "zemlja_podrijetla": "Francuska",
      "stoljeće_pojave": 19,
      "glazbeni_žanrovi": [
         "Narodna glazba",
         "Klasika"
      ],
      "dijelovi": [
         {
            "dio": "Tipke",
            "materijal": "Plastika"
         },
         {
            "dio": "Gumbi",
            "materijal": "Plastika"
         },
         {
            "dio": "Mjehov",
            "materijal": "Koža"
         }
      ],
      "način_sviranja": "Pritiskanjem tipki i gumba te stiskanjem mjeha dolazi do strujanja zraka stvarajući tonove određenih frekvencija",
      "najpoznatiji_izvođači": [
         "Peter Soave",
         "Franko Božac"
      ],
      "najpoznatiji_proizvođači": [
         "Franzu Friedrichu Buschmannu",
         "GOLDENCUP"
      ]
   }
]
